### ISSUE TITLE
Getting ServerParseError on  expo and graphql mock

### ISSUE THREAD

**Issue by Davete0302** [jefflau/jest-fetch-mock#224]
I'm using react-native with expo, jest-fetch-mock and graphql. When calling the api Im getting error

 × return user feed query (69ms)

  ● testing api › return user feed query

    Unexpected end of JSON input

       at _callee$ (graphql/__tests__/api.test.js:29:41)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:119:21)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (node_modules/regenerator-runtime/runtime.js:155:20)
      at node_modules/regenerator-runtime/runtime.js:165:13
      at tryCallOne (node_modules/react-native/node_modules/promise/lib/core.js:37:12)
      at node_modules/react-native/node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
      at node_modules/@jest/fake-timers/build/jestFakeTimers.js:496:18
      
  **api.test.js import fetch from 'jest-fetch-mock';**
    
```
      import fetch from 'jest-fetch-mock';

import { getUserFeed } from '../feed'

describe('testing api', () => {
    beforeEach(() => {
        fetch.resetMocks()
    })

    it('return user feed query', async () => {


        //assert on the response
        await getUserFeed(20).then((response) => response.json())
            .then((responseJson) => {
                console.log('res ' + JSON.stringify(responseJson))
            }).catch((error) => {
                console.log('error' + JSON.stringify(error))
            })

        // .then((res) => {
        //     console.log('res '+JSON.stringify(res))
        // }).catch((error) => {
        //     console.log('error'+JSON.stringify(error))
        //     })

        //assert on the times called and arguments given to fetch
        console.log('watch ' + JSON.stringify(fetch.mock.calls))
        expect(fetch.mock.calls.length).toEqual(20)
    })
```
})

**Comment by jefflau** [comment]
Closing during the 2026 triage: no reproduction materialized and the thread's gone quiet. If this still bites on 3.2.0, please open a fresh issue with a minimal repro.
