### ISSUE TITLE
Unexpected behaviour while mocking fetch failure case

### ISSUE THREAD

**Issue by iiison** [jefflau/jest-fetch-mock#43]
Hi, my successful mock call is working fine but I am getting this error in case of failure case:
```js
 ● >>> ACTIONS -- User Actions › • Asynchronous Action Creators › User Login Action Creator -- Failure

    Failed: Failed!

      at stackFormatter (node_modules/jest/node_modules/jest-cli/node_modules/jest-config/node_modules/jest-jasmine2/build/expectation_result_factory.js:49:427)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

Here the my test code:

```javascript
    test('User Login Action Creator -- Failure', () => {
      const expectedActions = [
        actions.fetchUser(),
        actions.unauthUser(),
        actions.fetchUserFailure()
      ]
      const store = mockStore({
        user : {}
      })

      fetch.mockReject(new Error('Failed!')) // 

      return store
        .dispatch(actions.userLogin({
          userName : '',
          password : ''
        }))
        .then(() => {
          expect(store.getActions()).toEqual(expectedActions)
        })
    })
```

I am not sure what am I missing here.

**Comment by AllenFang** [comment]
@iiison would you please print the `store.getActions()` ?!

**Comment by iiison** [comment]
I checked `store.getActions()`in catch block, and there it matches actions. But, is it the right way.. to check expected result in `catch` block? 🤔

**Comment by AllenFang** [comment]
> to check expected result in catch block?

no, That's not what I means

```js
return store
        .dispatch(actions.userLogin({
          userName : '',
          password : ''
        }))
        .then(() => {
          // I wanna see the value of store.getActions() here
          expect(store.getActions()).toEqual(expectedActions)
        })
```

BTW, usually, a practice is call `fetch.resetMocks();` after each test case to make sure you have clean mock states.

**Comment by iiison** [comment]
The control doesn't go to `then` it comes to the `catch` block, as I am throwing an error in case of network error.

**Comment by AllenFang** [comment]
@iiison I see, so what do you do in your promise catch? As expected, you are supposed to be send another failure action to Redux so that `fetch.mockReject(new Error('Failed!'))` will be effective. For example:

```js
export function fetchSomething(token) {
  return dispatch =>
    fetch(URL)
      .then(response => response.json())
      .then((json) => {
        if (json.data) {
          dispatch(fetchSomethingSuccess(json.data));
        }
      })
      .catch((e) => {
        // dispatch another error action
        dispatch({ type: API_ERROR, payload: e });
      });
}
```

so in your test case:

```js
it('should dispatching a correct action if fetching failure', () => {
      const message = 'fake error message';
      const fakeError = new Error(message);
      fetch.mockReject(fakeError);

      return store.dispatch(fetchSomething())
        .then(() => {
          const errorAction = store.getActions()[0];
          expect(errorAction).toBeDefined();
          expect(errorAction).toEqual({
            type: API_ERROR, payload: fakeError
          });
        });
    });
```

**Comment by jefflau** [comment]
Closing this discussion. Can reopen if OP wants to continue the discussion
